### ISSUE TITLE
Issues With .gitlab-ci.yml

### ISSUE THREAD

**Issue by hmajid2301** [arjun-g/vs-swagger-viewer#73]
I use GitLab CI, which is defined as a `yaml` file. I've noticed sometimes the Swagger Viewer Plugin raises a "problem" in this file for example in code below I have defined a job.

I'm using VSCode version: 1.38.1
Swagger Viewer: 2.2.2

```yaml
docker-scan:
  stage: test
  image:
    name: anchore/anchore-engine
    entrypoint: [""]
  services:
    - name: anchore/engine-db-preload:v0.3.0
      alias: anchore-db
  before_script: []
  script:
    - anchore_ci_tools --setup
    - anchore-cli registry add ${CI_REGISTRY} gitlab-ci-token ${CI_JOB_TOKEN} --skip-validate --insecure
    - anchore_ci_tools --analyze --report --image ${CI_REGISTRY_IMAGE}:test
    - mv anchore-reports/image-vuln-report.json anchore.json
  artifacts:
    paths:
      - anchore.json
```

The plugin raises the following problem (for the `script`) 

```
can not read a block mapping entry; a multiline key may not be an implicit key at line 98, column 9:
      script:
            ^Swagger Viewer Parse(0)
````

Thanks
